---

- hosts: localhost
  vars:
    docker_version: latest
    docker_daemon_json:
      log-driver: journald
      max-concurrent-downloads: 5
      max-concurrent-uploads: 5
  roles:
    - egeneralov.docker
