---

- hosts: docker
  vars:
    docker_version: 18.06.3~ce~3-0~debian
    docker_daemon_json:
      log-driver: journald
      max-concurrent-downloads: 5
      max-concurrent-uploads: 5
  roles:
    - egeneralov.docker
